global:
## Override the deployment namespace
#   namespaceOverride:

image:
  repository: 790762862953.dkr.ecr.eu-west-2.amazonaws.com/ecr-public/aws-observability/aws-for-fluent-bit
  tag: 2.31.6
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  ## Allow the service to be exposed for monitoring
  ## https://docs.fluentbit.io/manual/administration/monitoring
  # extraService: |
  #   HTTP_Server  On
  #   HTTP_Listen  0.0.0.0
  #   HTTP_PORT    2020
  parsersFiles:
    - /fluent-bit/parsers/parsers.conf
    - /fluent-bit/parsers/parsers_extra.conf
  extraParsers: |
    [PARSER]
      Name    kube-app
      Format  regex
      Regex   (?<tag>[^.]+)?\.?(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.log$

input:
  tag: "kube.*"
  path: "/var/log/containers/*.log"
  db: "/var/log/flb_kube.db"
  parser: cri
  dockerMode: "Off"
  memBufLimit: 5MB
  skipLongLines: "On"
  refreshInterval: 10
  
  extraInputs: |
    exclude_path /var/log/containers/*-log-fetcher-*.log

additionalInputs: |
    [INPUT]
        Name              tail
        Tag               app.*
        Path              /var/log/containers/*-log-fetcher-*.log
        DB                /var/log/flb_app.db
        Parser            cri
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10

filter:
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "data"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "On"
  # extraFilters: |
  #   ...

additionalFilters: |
    [FILTER]
        Name                kubernetes
        Match               app.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        Merge_Log_Key       data
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Buffer_Size         32k
        Kube_Tag_Prefix     app.var.log.containers.
    [FILTER]
        Name    parser
        Match app.*
        Key_Name message
        Parser json
        Reserve_data On  
    [FILTER]
        Name       record_modifier
        Match      app.*
        Remove_key logtag
        Remove_key stream
    [FILTER]
        Name        nest
        Match       app.*
        Operation   nest
        Nest_under  kubernetes
        Wildcard    app_log_file*

cloudWatch:
  enabled: true
  match: "kube.*"
  region: ${region}
  logGroupName: "$(kubernetes['namespace_name'])-$(kubernetes['container_name'])-output"
  logStreamName: "$(kubernetes['pod_name'])"
  logStreamPrefix: 
  logKey: message
  # By default, the whole log record will be sent to CloudWatch. 
  # If you specify a key name with this option, then only the value of that key 
  # will be sent to CloudWatch.
  logFormat:
  logRetentionDays: ${log_retention_in_days}
  roleArn:
  autoCreateGroup: true
  endpoint:
  credentialsEndpoint: {}
  # extraOutputs: |
  #   ...

firehose:
  enabled: false
  match: "*"
  region: 
  deliveryStream: "my-stream"
  dataKeys:
  roleArn:
  endpoint:
  timeKey:
  # extraOutputs: |
  #   ...

kinesis:
  enabled: false
  match: "*"
  region: 
  stream: "my-kinesis-stream-name"
  partitionKey: "container_id"
  appendNewline:
  replaceDots:
  dataKeys:
  roleArn:
  endpoint:
  stsEndpoint:
  timeKey:
  timeKeyFormat:
  compression:
  aggregation:
  experimental:
    concurrency:
    concurrencyRetries:
  # extraOutputs: |
  #   ...

elasticsearch:
  enabled: false
  match: "*"
  host:
  awsRegion: ${region}
  awsAuth: "On"
  tls: "On"
  port: "443"
  retryLimit: 6
  replaceDots: "On"
  # extraOutputs: |
  #   Index = my-index

additionalOutputs: |
    [OUTPUT]
        Name                  cloudwatch
        Match                 app.*
        region                ${region}
        log_group_name        $(kubernetes['namespace_name'])-$(kubernetes['labels']['app.kubernetes.io/instance'])/$(kubernetes['app_log_file'])
        log_stream_name       $(kubernetes['pod_name'])
        log_key               log
        log_retention_days    90
        auto_create_group     true

serviceAccount:
  create: true
  annotations: 
    eks.amazonaws.com/role-arn: ${iam_role_arn}
  name: fluentbit

resources:
  limits:
    memory: 250Mi
  requests:
    cpu: 50m
    memory: 50Mi

## Assign a PriorityClassName to pods if set
# priorityClassName: system-node-critical

updateStrategy:
  type: RollingUpdate

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}
  # iam.amazonaws.com/role: arn:aws:iam::123456789012:role/role-for-fluent-bit

env: []
## To add extra environment variables to the pods, add as below
# env:
#   - name: AWS_REGION
#     valueFrom:
#       configMapKeyRef:
#         name: fluent-bit-cluster-info
#         key: logs.region
#   - name: CLUSTER_NAME
#     valueFrom:
#       configMapKeyRef:
#         name: fluent-bit-cluster-info
#         key: cluster.name
#   - name: HOST_NAME
#     valueFrom:
#       fieldRef:
#         fieldPath: spec.nodeName


volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers

volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true

serviceMonitor:
  # service:
  #   type: ClusterIP
  #   port: 2020
  #   targetPort: 2020
  # When set true then use a ServiceMonitor to configure scraping
  enabled: false
  # Set the namespace the ServiceMonitor should be deployed
  # namespace: monitoring
  # Set how frequently Prometheus should scrape
  # interval: 30s
  # Set path of metrics, e.g /api/v1/metrics/prometheus
  # telemetryPath: /api/v1/metrics/prometheus
  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  # labels:
  # Set timeout for scrape
  # timeout: 10s
  # Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
  # relabelings: []
  # Set of labels to transfer on the Kubernetes Service onto the target.
  # targetLabels: []
  # metricRelabelings: []
